"use client";

import { memoToHtml, memoToMarkdown } from "@/lib/memo";
import { sampleDecisionMemo } from "@/lib/governance-data";
import { StatusBadge } from "./status-badge";
import { Button } from "./ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "./ui/card";

const memo = sampleDecisionMemo();
const download = (contents: string, type: string, fileName: string) => { const url = URL.createObjectURL(new Blob([contents], { type })); const link = document.createElement("a"); link.href = url; link.download = fileName; link.click(); URL.revokeObjectURL(url); };

export function DecisionMemoView() {
  const printMemo = () => { const printWindow = window.open("", "_blank"); if (!printWindow) return; printWindow.document.write(memoToHtml(memo)); printWindow.document.close(); printWindow.focus(); printWindow.print(); };
  return <div className="space-y-6">
    <div className="flex flex-wrap gap-2 print:hidden"><Button onClick={() => download(memoToMarkdown(memo), "text/markdown;charset=utf-8", "support-refund-decision.sample.md")}>Export Markdown</Button><Button variant="outline" onClick={() => download(memoToHtml(memo), "text/html;charset=utf-8", "support-refund-decision.sample.html")}>Export HTML</Button><Button variant="outline" onClick={printMemo}>Print / save PDF</Button></div>
    <p className="rounded-lg border border-amber-300 bg-amber-50 p-3 text-sm font-semibold text-amber-950">{memo.sampleLabel}</p>
    <Card className="border-red-200 bg-red-50"><CardContent className="flex flex-wrap items-center justify-between gap-4 pt-5"><div><p className="text-xs font-bold uppercase text-red-700">Final recorded decision</p><p className="text-2xl font-semibold text-red-950">{memo.finalDecision.outcome}</p><p className="mt-1 text-sm text-red-900">System recommendation retained: {memo.finalDecision.systemRecommendation}</p></div><StatusBadge status={memo.finalDecision.outcome}/></CardContent></Card>
    <div className="grid gap-4 lg:grid-cols-2"><Card><CardHeader><CardTitle>Product context</CardTitle></CardHeader><CardContent className="space-y-2 text-sm"><p>{memo.productContext.intendedValue}</p><p><strong>Owner:</strong> {memo.productContext.owner}</p><p><strong>Risk:</strong> {memo.productContext.riskLevel}</p><p><strong>Affected users:</strong> {memo.productContext.affectedUsers.join(", ")}</p><p><strong>Tools:</strong> {memo.productContext.tools.join(", ")}</p></CardContent></Card><Card><CardHeader><CardTitle>Evaluation scope</CardTitle></CardHeader><CardContent className="space-y-2 text-sm"><p><strong>Evidence:</strong> {memo.evaluationScope.evidenceVersion}</p><p><strong>Source:</strong> {memo.evaluationScope.source}</p><p>{memo.evaluationScope.scenarios}</p><p><strong>Accepted runs:</strong> {memo.evaluationScope.acceptedRuns} · {memo.evaluationScope.period}</p><p>Task success: 91 / 100 sample runs.</p><p>Recovery success: 5 / 12 sample recovery attempts (42%), below the assumed 80% blocking threshold.</p></CardContent></Card></div>
    <Card><CardHeader><CardTitle>Notable failures</CardTitle></CardHeader><CardContent className="grid gap-3 md:grid-cols-2">{memo.notableFailures.map((failure) => <article className="rounded-lg border p-3 text-sm" key={failure.id}><div className="flex items-center justify-between"><strong>{failure.id} · {failure.severity}</strong><StatusBadge status={failure.status}/></div><p className="mt-2">{failure.description}</p><p className="mt-2 text-xs text-slate-500">Owner: {failure.owner} · Evidence: {failure.evidenceReference}</p></article>)}</CardContent></Card>
    <Card><CardHeader><CardTitle>Gate results</CardTitle></CardHeader><CardContent className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="border-b"><th className="p-2">Gate</th><th className="p-2">Result</th><th className="p-2">Observed / policy</th><th className="p-2">Behavior</th><th className="p-2">Owner</th></tr></thead><tbody>{memo.gateResults.map((gate) => <tr className="border-b" key={gate.name}><td className="p-2 font-semibold">{gate.name}</td><td className="p-2"><StatusBadge status={gate.status}/></td><td className="p-2">{gate.observed} / {gate.policy}</td><td className="p-2">{gate.behavior}</td><td className="p-2">{gate.owner}</td></tr>)}</tbody></table></CardContent></Card>
    <div className="grid gap-4 lg:grid-cols-2"><Card><CardHeader><CardTitle>Unresolved risks</CardTitle></CardHeader><CardContent className="space-y-3">{memo.unresolvedRisks.map((risk) => <div className="rounded-lg border p-3 text-sm" key={risk.risk}><strong>{risk.risk}</strong><p>{risk.mitigation}</p><p className="mt-1 text-xs text-slate-500">{risk.owner} · {risk.dueDate}</p></div>)}</CardContent></Card><Card><CardHeader><CardTitle>Rollback triggers</CardTitle></CardHeader><CardContent><ul className="list-disc space-y-2 pl-5 text-sm">{memo.rollbackTriggers.map((trigger) => <li key={trigger}>{trigger}</li>)}</ul><p className="mt-4 text-sm"><strong>Next review:</strong> {memo.nextReviewDate}</p></CardContent></Card></div>
    <Card><CardHeader><CardTitle>Reviewer positions · disagreement preserved</CardTitle></CardHeader><CardContent className="grid gap-3 md:grid-cols-2">{memo.reviewerPositions.map((review) => <article className="rounded-lg border p-3" key={review.role}><div className="flex items-center justify-between"><strong>{review.role.replace("_", " / ")}</strong><StatusBadge status={review.disposition ?? "Not submitted"}/></div><p className="mt-1 text-xs text-slate-500">{review.reviewerName}</p><p className="mt-2 text-sm">{review.rationale}</p>{review.remediationRequests.map((request) => <p className="mt-2 rounded bg-amber-50 p-2 text-xs" key={request.request}>Remediation: {request.request} · {request.owner} · {request.dueDate}</p>)}</article>)}</CardContent></Card>
    <Card><CardHeader><CardTitle>Final decision rationale</CardTitle></CardHeader><CardContent className="space-y-2 text-sm"><p>{memo.finalDecision.rationale}</p><p><strong>Decision owner:</strong> {memo.finalDecision.decisionOwner}</p><p><strong>Recorded:</strong> {memo.finalDecision.decidedAt}</p></CardContent></Card>
    <Card><CardHeader><CardTitle>Complete audit timeline</CardTitle></CardHeader><CardContent><ol className="relative ml-2 border-l border-slate-300 pl-5">{memo.auditTimeline.map((event) => <li className="mb-5 last:mb-0" key={event.id}><span className="absolute -ml-[25px] mt-1 size-2 rounded-full bg-slate-700"/><div className="flex flex-wrap items-center gap-2"><span className="rounded bg-slate-100 px-2 py-0.5 text-[10px] font-bold">{event.source}</span><strong className="text-sm">{event.action}</strong></div><p className="mt-1 text-sm">{event.detail}</p><p className="mt-1 text-xs text-slate-500">{event.occurredAt} · {event.actor}</p></li>)}</ol></CardContent></Card>
  </div>;
}
