"use client";
import { useState } from "react";
import { taxonomyLabels } from "@/lib/evaluation-data";
import { Button } from "./ui/button";

type Failure={id:string;category:string;severity:string;testCase:string;owner:string;status:string;evidence:string;duplicateOf?:string; rationale?:string};
const initial:Failure[]=[
 {id:"F-014",category:"unrecovered_timeout",severity:"critical",testCase:"Refund API timeout",owner:"Platform team",status:"open",evidence:"refund-002"},
 {id:"F-015",category:"inconsistent_retry",severity:"high",testCase:"Refund API timeout",owner:"Unassigned",status:"open",evidence:"refund-002"},
 {id:"F-009",category:"hallucinated_tool_result",severity:"high",testCase:"Ineligible promotional purchase",owner:"Refunds team",status:"in_progress",evidence:"refund-003"},
];
export function FailureReview(){const [items,setItems]=useState(initial); const [selected,setSelected]=useState<string[]>([]); const [rationales,setRationales]=useState<Record<string,string>>({});
 const update=(id:string,patch:Partial<Failure>)=>setItems(v=>v.map(f=>f.id===id?{...f,...patch}:f));
 const merge=()=>{if(selected.length!==2)return; const [primary,duplicate]=selected; setItems(v=>v.map(f=>f.id===duplicate?{...f,duplicateOf:primary,status:"merged"}:f));setSelected([])};
 return <div className="space-y-4"><div className="flex flex-wrap items-center justify-between gap-3"><p className="text-sm text-slate-600">Select exactly two records to merge the second into the first. Evidence remains linked.</p><Button variant="outline" disabled={selected.length!==2} onClick={merge}>Merge selected duplicates</Button></div>{items.map(f=><article key={f.id} className={`rounded-xl border bg-white p-5 ${f.duplicateOf?"opacity-60":""}`}><div className="grid gap-4 lg:grid-cols-[32px_1.4fr_1fr_1fr]"><input aria-label={`Select ${f.id}`} type="checkbox" disabled={!!f.duplicateOf} checked={selected.includes(f.id)} onChange={e=>setSelected(s=>e.target.checked?[...s,f.id]:s.filter(id=>id!==f.id))}/><div><div className="flex flex-wrap items-center gap-2"><h2 className="font-semibold">{f.id} · {taxonomyLabels[f.category]}</h2>{f.duplicateOf&&<span className="rounded bg-slate-100 px-2 py-1 text-xs">Merged into {f.duplicateOf}</span>}</div><p className="mt-1 text-sm text-slate-600">{f.testCase} · Evidence: <a className="underline" href={`/evaluations/runs/${f.evidence}`}>{f.evidence}</a></p></div><label className="text-xs font-semibold text-slate-600">Owner<input className="mt-1 w-full rounded-md border p-2 text-sm font-normal" value={f.owner} onChange={e=>update(f.id,{owner:e.target.value})}/></label><label className="text-xs font-semibold text-slate-600">Remediation status<select className="mt-1 w-full rounded-md border p-2 text-sm font-normal" value={f.status} disabled={!!f.duplicateOf} onChange={e=>update(f.id,{status:e.target.value})}><option value="open">Open</option><option value="in_progress">In progress</option><option value="mitigated">Mitigated</option><option value="resolved">Resolved</option><option value="accepted">Risk accepted</option><option value="merged">Merged</option></select></label></div><div className="mt-4 grid gap-3 border-t pt-4 md:grid-cols-[180px_1fr]"><label className="text-xs font-semibold text-slate-600">Severity<select className="mt-1 w-full rounded-md border p-2 text-sm font-normal capitalize" value={f.severity} onChange={e=>{if(!rationales[f.id]?.trim())return;update(f.id,{severity:e.target.value,rationale:rationales[f.id]})}}><option>low</option><option>medium</option><option>high</option><option>critical</option></select></label><label className="text-xs font-semibold text-slate-600">Required rationale before changing severity<input className="mt-1 w-full rounded-md border p-2 text-sm font-normal" placeholder="Explain impact or evidence that changed" value={rationales[f.id]??""} onChange={e=>setRationales(r=>({...r,[f.id]:e.target.value}))}/></label></div></article>)}</div>}
