"use client";
import { useState } from "react";
import { Button } from "./ui/button";
import { parseCsvImport, validateCsvHeaders, validateImport, type ImportIssue, type ImportPreview } from "@/lib/validation";

export function ImportPreviewPanel() {
  const [preview,setPreview]=useState<ImportPreview|null>(null); const [confirmed,setConfirmed]=useState(false);
  async function choose(file:File) { setConfirmed(false); const text=await file.text(); let value:unknown; let headerIssues:ImportIssue[]=[]; try { if(file.name.toLowerCase().endsWith(".csv")){ headerIssues=validateCsvHeaders(text); value=parseCsvImport(text,file.name,false); } else value=JSON.parse(text); const next=validateImport(value); setPreview({...next,issues:[...headerIssues,...next.issues]}); } catch(e){ setPreview({sourceName:file.name,isSample:false,rows:[],issues:[{row:null,field:"file",message:e instanceof Error?e.message:"Could not read file"}]}); } }
  return <section className="rounded-xl border bg-white p-5" aria-labelledby="import-title"><div className="flex flex-col gap-4 md:flex-row md:items-end md:justify-between"><div><h2 id="import-title" className="font-semibold">Import evaluation run</h2><p className="mt-1 text-sm text-slate-600">Select JSON or CSV. Validation runs locally; review the preview before persistence.</p></div><label className="inline-flex h-10 cursor-pointer items-center rounded-md border px-4 text-sm font-semibold hover:bg-slate-50">Choose file<input className="sr-only" type="file" accept=".json,.csv,application/json,text/csv" onChange={e=>e.target.files?.[0]&&choose(e.target.files[0])}/></label></div>
  {preview&&<div className="mt-5" aria-live="polite">{preview.issues.length>0?<div className="rounded-lg border border-red-200 bg-red-50 p-4"><h3 className="font-semibold text-red-950">Import blocked · {preview.issues.length} validation error{preview.issues.length===1?"":"s"}</h3><ul className="mt-3 space-y-2 text-sm text-red-900">{preview.issues.map((e,i)=><li key={i}><strong>{e.row?`Row ${e.row}`:"File"} · {e.field}:</strong> {e.message}</li>)}</ul></div>:<><div className="rounded-lg border border-emerald-200 bg-emerald-50 p-4"><h3 className="font-semibold text-emerald-950">Ready to persist · {preview.rows.length} valid rows</h3><p className="text-sm text-emerald-900">Source: {preview.sourceName} · {preview.isSample?"Sample data":"User-provided data"}</p></div><div className="mt-3 overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="border-b">{["Run","Test case","Result","Severity","Latency","Cost"].map(h=><th className="p-2" key={h}>{h}</th>)}</tr></thead><tbody>{preview.rows.slice(0,5).map(r=><tr className="border-b" key={r.run_id}><td className="p-2 font-mono text-xs">{r.run_id}</td><td className="p-2">{r.test_case}</td><td className="p-2">{r.passed?"Pass":"Fail"}</td><td className="p-2 capitalize">{r.severity??"—"}</td><td className="p-2">{r.latency_ms} ms</td><td className="p-2">${r.cost_usd.toFixed(3)}</td></tr>)}</tbody></table></div><div className="mt-4 flex items-center gap-3"><Button onClick={()=>setConfirmed(true)}>Persist {preview.rows.length} rows</Button><span className="text-sm text-slate-500">Creates a new evidence version; never replaces a prior snapshot.</span></div>{confirmed&&<p className="mt-3 rounded bg-amber-50 p-3 text-sm text-amber-900">Preview confirmed. Persistence is intentionally represented as an MVP handoff until database-backed route handlers are connected.</p>}</>}</div>}</section>;
}
