"use client";

import { useMemo, useState } from "react";
import { finalizationReadiness, recordCriticalRoleException, reviewDisagreement, submitReview, type ReviewDisposition, type ReviewRole, type RoleReview } from "@/lib/reviews";
import { sampleCriticalRoleExceptions, sampleRoleReviews } from "@/lib/governance-data";
import { StatusBadge } from "./status-badge";
import { Button } from "./ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "./ui/card";

const roleLabels: Record<ReviewRole, string> = { PRODUCT: "Product", ENGINEERING: "Engineering", TRUST_SAFETY: "Trust / safety", OPERATIONS: "Operations" };
const field = "h-10 rounded-md border bg-white px-3 text-sm";

export function ReviewWorkbench() {
  const [reviews, setReviews] = useState(sampleRoleReviews);
  const [selectedRole, setSelectedRole] = useState<ReviewRole>("PRODUCT");
  const [comment, setComment] = useState({ evidenceReference: "", comment: "" });
  const [request, setRequest] = useState({ request: "", owner: "", dueDate: "" });
  const [exceptions, setExceptions] = useState(sampleCriticalRoleExceptions);
  const [exception, setException] = useState({ role: "OPERATIONS" as ReviewRole, rationale: "", approvedBy: "" });
  const [message, setMessage] = useState("");
  const review = reviews.find((item) => item.role === selectedRole)!;
  const readiness = useMemo(() => finalizationReadiness(reviews, exceptions), [reviews, exceptions]);
  const disagreement = useMemo(() => reviewDisagreement(reviews), [reviews]);
  const update = (patch: Partial<RoleReview>) => setReviews((current) => current.map((item) => item.role === selectedRole ? { ...item, ...patch } : item));
  const save = () => { try { const submitted = submitReview(review); setReviews((current) => current.map((item) => item.role === selectedRole ? submitted : item)); setMessage(`Review submitted by ${submitted.reviewerName}. Audit event ROLE_REVIEW_SUBMITTED created locally.`); } catch (error) { setMessage(error instanceof Error ? error.message : "Review could not be submitted"); } };
  const addComment = () => { if (!comment.evidenceReference.trim() || !comment.comment.trim()) return setMessage("Evidence reference and comment are required"); update({ evidenceComments: [...review.evidenceComments, comment] }); setComment({ evidenceReference: "", comment: "" }); setMessage("Evidence comment added to the draft review."); };
  const addRequest = () => { if (!request.request.trim() || !request.owner.trim() || !request.dueDate) return setMessage("Remediation request, owner, and due date are required"); update({ remediationRequests: [...review.remediationRequests, request] }); setRequest({ request: "", owner: "", dueDate: "" }); setMessage("Remediation request added to the draft review."); };
  const addException = () => { try { const recorded = recordCriticalRoleException(exception); setExceptions((current) => [...current, recorded]); setException({ ...exception, rationale: "", approvedBy: "" }); setMessage(`Critical-role exception recorded for ${roleLabels[recorded.role]}; audit event required on persistence.`); } catch (error) { setMessage(error instanceof Error ? error.message : "Exception could not be recorded"); } };

  return <div className="space-y-6">
    <div role="tablist" aria-label="Reviewer role" className="grid gap-2 sm:grid-cols-4">{reviews.map((item) => <button role="tab" aria-selected={selectedRole === item.role} className={`rounded-lg border p-3 text-left ${selectedRole === item.role ? "border-slate-900 bg-slate-900 text-white" : "bg-white"}`} key={item.role} onClick={() => { setSelectedRole(item.role); setMessage(""); }}><span className="block text-sm font-semibold">{roleLabels[item.role]}</span><span className={`text-xs ${selectedRole === item.role ? "text-slate-300" : "text-slate-500"}`}>{item.reviewerName} · {item.disposition ?? "Draft"}</span></button>)}</div>
    <Card><CardHeader><CardTitle>{roleLabels[selectedRole]} review view</CardTitle></CardHeader><CardContent className="space-y-5">
      <div className="grid gap-3 md:grid-cols-2"><label className="grid gap-1 text-xs font-semibold">Reviewer identity<input className={field} value={review.reviewerName} onChange={(event) => update({ reviewerName: event.target.value })}/></label><label className="grid gap-1 text-xs font-semibold">Accountable position<select className={field} value={review.disposition ?? ""} onChange={(event) => update({ disposition: event.target.value as ReviewDisposition })}><option value="" disabled>Select a position</option><option value="APPROVE">Approve</option><option value="REJECT">Reject</option><option value="ABSTAIN">Abstain</option></select></label></div>
      <label className="grid gap-1 text-xs font-semibold">Required rationale<textarea className="min-h-24 rounded-md border p-3 text-sm" value={review.rationale} onChange={(event) => update({ rationale: event.target.value })}/></label>
      <div className="grid gap-4 lg:grid-cols-2"><section className="rounded-lg border p-4"><h3 className="font-semibold">Comment on evidence</h3><div className="mt-3 grid gap-2"><input aria-label="Evidence reference" placeholder="Evidence reference, e.g. refund-002" className={field} value={comment.evidenceReference} onChange={(event) => setComment({ ...comment, evidenceReference: event.target.value })}/><textarea aria-label="Evidence comment" placeholder="What does this evidence change or leave uncertain?" className="min-h-20 rounded-md border p-3 text-sm" value={comment.comment} onChange={(event) => setComment({ ...comment, comment: event.target.value })}/><Button variant="outline" onClick={addComment}>Add evidence comment</Button></div><ul className="mt-3 space-y-2 text-sm">{review.evidenceComments.map((item, index) => <li className="rounded bg-slate-100 p-2" key={`${item.evidenceReference}-${index}`}><strong>{item.evidenceReference}</strong> — {item.comment}</li>)}</ul></section>
      <section className="rounded-lg border p-4"><h3 className="font-semibold">Request remediation</h3><div className="mt-3 grid gap-2"><input aria-label="Remediation request" placeholder="Specific action or evidence needed" className={field} value={request.request} onChange={(event) => setRequest({ ...request, request: event.target.value })}/><div className="grid grid-cols-2 gap-2"><input aria-label="Remediation owner" placeholder="Owner" className={field} value={request.owner} onChange={(event) => setRequest({ ...request, owner: event.target.value })}/><input aria-label="Remediation due date" className={field} type="date" value={request.dueDate} onChange={(event) => setRequest({ ...request, dueDate: event.target.value })}/></div><Button variant="outline" onClick={addRequest}>Add remediation request</Button></div><ul className="mt-3 space-y-2 text-sm">{review.remediationRequests.map((item, index) => <li className="rounded bg-slate-100 p-2" key={`${item.request}-${index}`}><strong>{item.request}</strong><br/>{item.owner} · {item.dueDate}</li>)}</ul></section></div>
      {message && <p aria-live="polite" className="rounded bg-amber-50 p-3 text-sm text-amber-950">{message}</p>}<Button onClick={save}>Submit accountable review</Button>
    </CardContent></Card>
    <Card className={disagreement.disagree ? "border-amber-300" : ""}><CardHeader><CardTitle>{disagreement.disagree ? "Material disagreement is unresolved" : "Reviewer positions"}</CardTitle></CardHeader><CardContent><div className="grid gap-3 md:grid-cols-2">{disagreement.positions.map((position) => <div className="rounded-lg border p-3" key={position.role}><div className="flex items-center justify-between"><strong>{roleLabels[position.role]}</strong><StatusBadge status={position.disposition}/></div><p className="mt-2 text-sm text-slate-600">{position.reviewerName}: {position.rationale}</p></div>)}</div><p className="mt-4 text-sm font-semibold">Finalization: {readiness.ready ? "all designated critical roles submitted or excepted" : `blocked; missing ${readiness.missingCriticalRoles.map((role) => roleLabels[role]).join(", ")}`}.</p><details className="mt-4 rounded-lg border p-3"><summary className="cursor-pointer text-sm font-semibold">Document a critical-role exception</summary><p className="mt-2 text-xs text-slate-500">Use only when a designated critical review cannot be submitted. The exception remains visible and auditable.</p><div className="mt-3 grid gap-2 md:grid-cols-3"><select aria-label="Exception role" className={field} value={exception.role} onChange={(event) => setException({ ...exception, role: event.target.value as ReviewRole })}>{reviews.filter((item) => item.designatedCritical).map((item) => <option value={item.role} key={item.role}>{roleLabels[item.role]}</option>)}</select><input aria-label="Exception rationale" className={field} placeholder="Required rationale" value={exception.rationale} onChange={(event) => setException({ ...exception, rationale: event.target.value })}/><input aria-label="Exception approver" className={field} placeholder="Approver identity" value={exception.approvedBy} onChange={(event) => setException({ ...exception, approvedBy: event.target.value })}/></div><Button className="mt-3" variant="outline" onClick={addException}>Record exception</Button>{exceptions.map((item) => <p className="mt-2 rounded bg-amber-50 p-2 text-xs" key={`${item.role}-${item.recordedAt}`}>{roleLabels[item.role]} exception · {item.rationale} · Approved by {item.approvedBy} · {item.recordedAt}</p>)}</details></CardContent></Card>
  </div>;
}
