import Link from "next/link";
import { PageHeader } from "@/components/page-header";
import { StatusBadge } from "@/components/status-badge";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { calculateAnalytics } from "@/lib/analytics";
import { seededAnalyticsRecords } from "@/lib/analytics-data";
import { workflows } from "@/lib/sample-data";

const summary = calculateAnalytics(seededAnalyticsRecords);
const percent = (value?: number) => value === undefined ? "Insufficient evidence" : `${Math.round(value * 100)}%`;

const metrics = [
  { name: "Time to decision", value: summary.timeToDecision.medianHours === undefined ? "Insufficient evidence" : `${summary.timeToDecision.medianHours}h`, detail: `${summary.timeToDecision.decidedRecords} recorded decisions`, definition: "Median elapsed hours from review-ready timestamp to recorded decision; open reviews are excluded.", decision: "Shows where coordinators should investigate evidence, reviewer, or remediation wait time before trying to accelerate the process." },
  { name: "Gate failure rate", value: percent(summary.gateFailure.rate), detail: `${summary.gateFailure.failed} failed / ${summary.gateFailure.evaluated} evaluable gates`, definition: "Failed gates divided by Passed plus Failed gates. Insufficient Evidence is excluded and reported through evidence completeness.", decision: "Shows whether release policy is commonly stopping the seeded review set and which gate owners need remediation capacity or policy review." },
  { name: "Unresolved severe failures", value: String(summary.unresolvedSevereFailures.count), detail: `${summary.unresolvedSevereFailures.critical} critical · high and critical only`, definition: "Open or mitigating High/Critical failures across the seeded review records; resolved failures are excluded.", decision: "Identifies safety or reliability conditions that must be resolved, mitigated, or explicitly blocked before release." },
  { name: "Reviewer disagreement", value: percent(summary.reviewerDisagreement.rate), detail: `${summary.reviewerDisagreement.records} / ${summary.reviewerDisagreement.reviewedRecords} records with conflicting positions`, definition: "Review records with more than one distinct submitted position divided by records with any submitted review.", decision: "Surfaces decisions needing explicit conflict resolution; disagreement is preserved, not scored or averaged." },
  { name: "Evidence completeness", value: percent(summary.evidenceCompleteness.rate), detail: `${summary.evidenceCompleteness.complete} complete / ${summary.evidenceCompleteness.required} required items`, definition: "Valid, present required evidence items divided by policy-required items across the seeded review set.", decision: "Shows whether a decision can be defended or should remain Investigate while specific evidence is collected." },
] as const;

export default function DashboardPage() {
  const distribution = ["SHIP", "INVESTIGATE", "BLOCK"] as const;
  return <div className="space-y-7"><PageHeader eyebrow="Decision workspace · Seeded demo analytics" title="Launch decision health" description="Use process, evidence, policy, severe-risk, and disagreement signals to decide where a review needs intervention. These fictional records are not product or customer outcomes."/>
    <p className="rounded-lg border border-amber-300 bg-amber-50 p-3 text-sm font-semibold text-amber-950">SEEDED DEMO DATA · Four fictional review records with placeholder timestamps, policies, failures, and decisions.</p>
    <section aria-labelledby="decision-metrics"><div className="mb-3"><h2 id="decision-metrics" className="text-lg font-semibold">Decision-support metrics</h2><p className="text-sm text-slate-600">Each metric includes its denominator and the product decision it supports.</p></div><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{metrics.map((metric) => <Card key={metric.name}><CardHeader><CardTitle>{metric.name}</CardTitle></CardHeader><CardContent className="space-y-3"><div><p className="text-3xl font-semibold">{metric.value}</p><p className="text-xs text-slate-500">{metric.detail}</p></div><div className="border-t pt-3 text-xs leading-5"><p><strong>Definition:</strong> {metric.definition}</p><p className="mt-2"><strong>Decision supported:</strong> {metric.decision}</p></div></CardContent></Card>)}
      <Card><CardHeader><CardTitle>Decision distribution</CardTitle></CardHeader><CardContent className="space-y-3"><p className="text-xs text-slate-500">{summary.decisionDistribution.total} recorded seeded decisions; open reviews excluded</p>{distribution.map((outcome) => { const count = summary.decisionDistribution[outcome]; const width = summary.decisionDistribution.total ? count / summary.decisionDistribution.total * 100 : 0; return <div key={outcome}><div className="mb-1 flex justify-between text-xs font-semibold"><span>{outcome}</span><span>{count}</span></div><div className="h-2 rounded bg-slate-100"><div className={`h-2 rounded ${outcome === "SHIP" ? "bg-emerald-600" : outcome === "BLOCK" ? "bg-red-600" : "bg-amber-500"}`} style={{ width: `${width}%` }}/></div></div>; })}<div className="border-t pt-3 text-xs leading-5"><p><strong>Definition:</strong> Count of recorded Ship, Investigate, and Block outcomes; no quality ranking or composite score.</p><p className="mt-2"><strong>Decision supported:</strong> Checks whether the review process is producing actionable dispositions and prompts investigation of unusual shifts without treating Ship volume as success.</p></div></CardContent></Card>
    </div></section>
    <Card><CardHeader><CardTitle>Decision queue</CardTitle></CardHeader><CardContent className="divide-y p-0 pt-0">{workflows.map((workflow) => <Link className="grid gap-3 p-5 hover:bg-slate-50 md:grid-cols-[1fr_auto_auto] md:items-center" href={`/workflows/${workflow.slug}`} key={workflow.slug}><div><div className="flex items-center gap-2"><h3 className="font-semibold">{workflow.name}</h3><span className="rounded bg-amber-100 px-1.5 py-0.5 text-[10px] font-bold text-amber-900">SAMPLE</span></div><p className="mt-1 text-sm text-slate-500">{workflow.owner} · {workflow.risk} risk</p></div><p className="text-sm text-slate-600">{workflow.successRate}% task success</p><StatusBadge status={workflow.decision}/></Link>)}</CardContent></Card>
  </div>;
}
